CREATE TABLE [dbo].[HTMLContent]
(
	[HTMLContentId] INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    [HTMLContent] NVARCHAR(MAX) NOT NULL, 
    [InsertBy] NVARCHAR(50) NOT NULL, 
    [LastModified] DATETIMEOFFSET NOT NULL
)
